# Generated by Django 3.0.8 on 2020-08-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoOutgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Description', models.TextField(max_length=100)),
                ('Forwarded_by', models.CharField(max_length=50)),
                ('Forwarded_to', models.CharField(max_length=50)),
                ('Received_by', models.CharField(max_length=50)),
                ('Id_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Employee')),
            ],
            options={
                'db_table': 'MemoOutgoing',
            },
        ),
        migrations.CreateModel(
            name='MemoIngoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Description', models.TextField(max_length=100)),
                ('Receive_From', models.CharField(max_length=50)),
                ('Receive_By', models.CharField(max_length=50)),
                ('Id_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Employee')),
            ],
            options={
                'db_table': 'MemoIngoing',
            },
        ),
    ]
