# Generated by Django 3.0.8 on 2020-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemoRouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo_routing',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
