# Generated by Django 3.0.8 on 2020-08-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makeup_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College', models.CharField(max_length=20)),
                ('Reason', models.TextField(max_length=100)),
                ('OfferCode', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=20)),
                ('Room', models.CharField(max_length=20)),
                ('Date_Of', models.DateField()),
                ('Id_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Employee')),
            ],
            options={
                'db_table': 'Makeup_Class',
            },
        ),
    ]
