# Generated by Django 3.0.8 on 2020-07-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifacate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Form')),
            ],
        ),
    ]
