# Generated by Django 3.0.8 on 2020-07-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReqSlipNo', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Department', models.CharField(max_length=100)),
                ('Time_in', models.TimeField()),
                ('Time_out', models.TimeField()),
                ('Paper_Type', models.CharField(max_length=20)),
                ('No_of_Copies', models.IntegerField()),
                ('Size', models.CharField(max_length=20)),
                ('File', models.ImageField(upload_to='pictures')),
                ('Form_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Form')),
            ],
        ),
    ]
