# Generated by Django 3.0.8 on 2020-07-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=100)),
                ('Employee_Status', models.CharField(max_length=20)),
                ('Date_Start', models.DateField()),
                ('Date_End', models.DateField()),
                ('Period_Days', models.IntegerField()),
                ('Reason', models.TextField(max_length=100)),
                ('Form_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Form')),
            ],
        ),
    ]
